# Generated by Django 3.0.7 on 2020-06-18 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20200618_1821'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='upload',
            field=models.ImageField(upload_to='uploads/%Y/%m/%d/'),
        ),
    ]
