# Generated by Django 3.0.7 on 2020-06-18 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20200618_1822'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='upload',
            field=models.ImageField(blank=True, upload_to='avatars'),
        ),
    ]
