# Generated by Django 3.0.7 on 2020-06-19 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20200619_0741'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='upload',
            field=models.ImageField(blank=True, upload_to='avatars'),
        ),
    ]
